import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { pathToFileURL } from 'node:url';
import matter from 'gray-matter';

export function parsePost(raw, filename) {
  const { data, content } = matter(raw);
  const fail = (message) => {
    throw new Error(filename + ': ' + message);
  };
  const slug = basename(filename, '.md');
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))
    fail('Filename must use lowercase words separated by single hyphens.');
  for (const key of ['title', 'description'])
    if (typeof data[key] !== 'string' || !data[key].trim())
      fail('Missing or empty "' + key + '" in front matter.');
  if (typeof data.date !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(data.date))
    fail('Use a quoted date in YYYY-MM-DD format.');
  const date = new Date(data.date + 'T00:00:00Z');
  if (
    !Number.isFinite(date.getTime()) ||
    date.toISOString().slice(0, 10) !== data.date
  )
    fail('Date is not a real calendar date.');
  if (typeof data.draft !== 'boolean')
    fail('Set draft explicitly to true or false.');
  if (
    !Array.isArray(data.tags) ||
    data.tags.some((tag) => typeof tag !== 'string' || !tag.trim())
  )
    fail('Tags must be a list of non-empty strings.');
  if (!content.trim()) fail('The article body is empty.');
  return {
    slug,
    title: data.title.trim(),
    description: data.description.trim(),
    date: data.date,
    tags: data.tags.map((t) => t.trim()),
    draft: data.draft,
    body: content.trim(),
    readingMinutes: Math.max(
      1,
      Math.ceil(content.trim().split(/\s+/).length / 220),
    ),
  };
}

export function selectPosts(
  all,
  { includeDrafts = false, today = new Date().toISOString().slice(0, 10) } = {},
) {
  const seen = new Set();
  for (const post of all) {
    if (seen.has(post.slug))
      throw new Error('Duplicate article slug: ' + post.slug);
    seen.add(post.slug);
  }
  return all
    .filter((p) => includeDrafts || (!p.draft && p.date <= today))
    .sort(
      (a, b) => b.date.localeCompare(a.date) || a.slug.localeCompare(b.slug),
    );
}

export function buildPosts({
  root = process.cwd(),
  includeDrafts = false,
  today = new Date().toISOString().slice(0, 10),
} = {}) {
  const directory = resolve(root, 'content/posts');
  mkdirSync(directory, { recursive: true });
  const all = readdirSync(directory)
    .filter((f) => f.endsWith('.md'))
    .map((f) => parsePost(readFileSync(resolve(directory, f), 'utf8'), f));
  const visible = selectPosts(all, { includeDrafts, today });
  const output = resolve(root, 'lib/posts.generated.ts');
  const source =
    "// Generated by scripts/content.mjs. Edit content/posts/*.md instead.\nimport type { Post } from './post-types';\nexport const isDraftPreview = " +
    JSON.stringify(includeDrafts) +
    ';\nexport const posts: Post[] = ' +
    JSON.stringify(visible, null, 2) +
    ';\n';
  mkdirSync(dirname(output), { recursive: true });
  let previous;
  try {
    previous = readFileSync(output, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  if (previous !== source) writeFileSync(output, source);
  return { published: visible.length, excluded: all.length - visible.length };
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  const production = process.argv.includes('--production');
  const includeDrafts =
    !production && process.env.JOURNAL_DRAFT_PREVIEW === '1';
  const result = buildPosts({ includeDrafts });
  console.log(
    (includeDrafts ? 'LOCAL DRAFT PREVIEW' : 'Journal') +
      ': ' +
      result.published +
      ' visible article(s), ' +
      result.excluded +
      ' excluded.',
  );
}
